"""
Check that each Panel A variable mean is within 10% of Dittmann & Maug (2007) Table I.

Requires real ExecuComp parquet files in data/raw/. Skips automatically if data is missing.

AI-GENERATED: This file was generated by Claude (Anthropic).
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.append(str(Path(__file__).resolve().parents[1] / "src/py"))

from schemas import RunConfig

DATA_DIR = Path(__file__).resolve().parents[1] / "data" / "raw" / "execucomp"
REQUIRED_FILES = ["anncomp.parquet", "coperol.parquet", "codirfin.parquet", "stgrttab.parquet"]

has_data = all((DATA_DIR / f).exists() for f in REQUIRED_FILES)
skip_reason = "Real ExecuComp parquet files not found in data/raw/"

# Paper Table I Panel A means (from Dittmann & Maug 2007)
PAPER_PANEL_A = {
    "phi": 2037.0,       # Base salary ($'000)
    "nS": 2.29,          # Stock (%)
    "nO": 1.29,          # Options (%)
    "nOexp(-dT)": 1.22,  # Options adjusted (%)
    "nSP0": 91.98,       # Value of stock ($ m)
    "nOBS": 29.47,       # Value of options ($ m)
    "P0": 9857.0,        # Market value ($ m)
    "W0": 34.60,         # Wealth ($ m)
    "N(d1)": 0.834,      # Option delta
    "T": 5.89,           # Maturity (years)
    "sigma": 0.377,      # Volatility
}

TOLERANCE = 0.10  # 10% relative tolerance


@pytest.fixture(scope="module")
def panel_a_means():
    """Run the pipeline once and return Panel A means as a dict keyed by symbol."""
    from pipeline import run_pipeline

    config = RunConfig(
        reference_year=1999,
        history_years=5,
        data_dir=DATA_DIR,
        output_dir=Path("/tmp/dm_test_output"),
    )
    result = run_pipeline(config)
    rep = result.replicated_table1
    panel_a = rep[rep["panel"] == "A"]
    return dict(zip(panel_a["symbol"], panel_a["mean"]))


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_panel_a_sample_size():
    """Panel A sample size must be exactly 598."""
    from pipeline import run_pipeline

    config = RunConfig(
        reference_year=1999,
        history_years=5,
        data_dir=DATA_DIR,
        output_dir=Path("/tmp/dm_test_output"),
    )
    result = run_pipeline(config)
    import pandas as pd
    panel_a = result.contracts[pd.to_numeric(result.contracts["BS"], errors="coerce").gt(0.0)]
    assert len(panel_a) == 598, f"Panel A N={len(panel_a)}, expected 598"


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_phi_within_10pct(panel_a_means):
    """Base salary mean within 10% of paper."""
    assert panel_a_means["phi"] == pytest.approx(PAPER_PANEL_A["phi"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_nS_within_10pct(panel_a_means):
    """Stock (%) mean within 10% of paper."""
    assert panel_a_means["nS"] == pytest.approx(PAPER_PANEL_A["nS"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_nO_within_10pct(panel_a_means):
    """Options (%) mean within 10% of paper."""
    assert panel_a_means["nO"] == pytest.approx(PAPER_PANEL_A["nO"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_nO_adjusted_within_10pct(panel_a_means):
    """Options adjusted (%) mean within 10% of paper."""
    assert panel_a_means["nOexp(-dT)"] == pytest.approx(PAPER_PANEL_A["nOexp(-dT)"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_nSP0_within_10pct(panel_a_means):
    """Value of stock ($ m) mean within 10% of paper."""
    assert panel_a_means["nSP0"] == pytest.approx(PAPER_PANEL_A["nSP0"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_nOBS_within_10pct(panel_a_means):
    """Value of options ($ m) mean within 10% of paper."""
    assert panel_a_means["nOBS"] == pytest.approx(PAPER_PANEL_A["nOBS"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_P0_within_10pct(panel_a_means):
    """Market value ($ m) mean within 10% of paper."""
    assert panel_a_means["P0"] == pytest.approx(PAPER_PANEL_A["P0"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_W0_within_10pct(panel_a_means):
    """Wealth ($ m) mean within 10% of paper."""
    assert panel_a_means["W0"] == pytest.approx(PAPER_PANEL_A["W0"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_Nd1_within_10pct(panel_a_means):
    """Option delta mean within 10% of paper."""
    assert panel_a_means["N(d1)"] == pytest.approx(PAPER_PANEL_A["N(d1)"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_T_within_10pct(panel_a_means):
    """Maturity (years) mean within 10% of paper."""
    assert panel_a_means["T"] == pytest.approx(PAPER_PANEL_A["T"], rel=TOLERANCE)


@pytest.mark.skipif(not has_data, reason=skip_reason)
def test_sigma_within_10pct(panel_a_means):
    """Volatility mean within 10% of paper."""
    assert panel_a_means["sigma"] == pytest.approx(PAPER_PANEL_A["sigma"], rel=TOLERANCE)
